name: terraform
on:
  push:
    branches:
      - dev
      - release/**
      - master
    tags:
      - "v*"

jobs:
  get-env:
    name: Get environment
    runs-on: ubuntu-latest
    outputs:
      phase: ${{ steps.setvars.outputs.phase }}
    steps:
      - name: Set variables
        id: setvars
        run: |
              echo "GITHUB_BASE_REF: ${GITHUB_BASE_REF}
              if [ ${GITHUB_BASE_REF} == "master" ]; then
                echo "::set-output name=phase::prod"
              elif [[ ${GITHUB_BASE_REF} == release/* ]]; then
                echo "::set-output name=phase::test"
              elif [ ${GITHUB_BASE_REF} == "dev" ]; then
                echo "::set-output name=phase::dev"
              fi
